### PR TITLE
Using Etleap Cached depencies

### PR DESCRIPTION
**Pull request by caiusb**
We've seen issues with downloading the depencies from Maven, so for we are caching them in our S3 bucket.

I have tested the change in an Amazon Linux 2 VM, and the kinesis installs correctly. Before merging, I will spin up a new EMR cluster, and confirm that the bootstrap step succeeds. 

Story: [Cache Kinesis Maven dependencies](https://www.pivotaltracker.com/story/show/179392633)

### CODE REVIEW

**Review by romming — COMMENTED** [review]
Would solve the problem, but not crazy about the dependency on an Etleap S3 bucket to work.  Could we create a release artifact from this repo instead, put that in S3, and use that in our bootstrap instead?

**Comment by caiusb** [comment]
If we put in GitHub, that will be enough, as the install script can pull it directly from there.

**Comment by romming** [comment]
> If we put in GitHub, that will be enough, as the install script can pull it directly from there.

Ideally we only depend on S3, no external websites.

**Comment by caiusb** [comment]
Deprecated by #5.

**Pull request closed without merging**
